Fix settings handling
os-autoinst/openQA-python-client pull request #17
Opened 2021-04-26 12:31 UTC by dcermak

2021-04-26 13:31 UTC, okurz commented
@AdamWill weren't there tests for this repo? https://github.com/os-autoinst/openQA-python-client/actions/runs/785550285 shows

```
actions/checkout@v1 and actions/setup-python@v1 are not allowed to be used in os-autoinst/openQA-python-client. Actions in this workflow must be: within a repository owned by os-autoinst.
```

any idea?

2021-04-26 13:57 UTC, dcermak commented
Sounds like more restrictive permissions being applied here?

2021-04-26 14:52 UTC, AdamWill commented
oh, I set permissions more restrictive because of a thing I read about where people are exploiting PRs to make github actions mine crypto, but apparently that won't work. guess I'll change it back.

2021-04-26 15:02 UTC, okurz commented on tests/test_client.py
> +        assert len(fakeresp.method_calls) == 0
assert can take a second argument which I recommend to use, also see https://wiki.python.org/moin/UsingAssertionsEffectively , e.g.

```suggestion
        assert len(fakeresp.method_calls) == 0, 'invalid method call on response (or something)'
```

2021-04-26 15:02 UTC, okurz commented on tests/test_client.py
> +        assert ret == fakesend.return_value
same here then

2021-04-26 15:02 UTC, okurz commented
@AdamWill yeah we actually had that case of crypto miner exploitation PRs on os-autoinst

2021-04-27 08:58 UTC, okurz requested changes

2021-04-27 08:58 UTC, okurz commented on tests/test_client.py
> +        # check that we returned the request object
I meant that you actually don't need the comments anymore if the assert call speaks for itself :)

2021-04-27 14:28 UTC, okurz approved these changes

2021-04-27 14:28 UTC, merged

2021-04-27 16:23 UTC, okurz commented
@AdamWill can you do a new release on PyPi of https://github.com/os-autoinst/openQA-python-client/releases/tag/4.1.2 ?

2021-04-27 17:08 UTC, AdamWill commented
Er, well it's a bit harder now you've tagged it :( You also didn't update `CHANGELOG.md`. There's a `release.sh` script in the repo which is supposed to be used to do releases. Can you please just ping me next time?

2021-04-27 17:08 UTC, AdamWill commented
you didn't update `setup.py` or `__init__.py` either...all the things the script does...

2021-04-27 17:13 UTC, AdamWill commented
okay, I wiped the 4.1.2 tag and started over, release should be done correctly now.

2021-04-27 18:14 UTC, okurz commented
sorry